export class TeamList {
    constructor(
        public id: number,
        public fll_number: number,
        public team_name: string,       
        public created_at: Date,
        public updated_at: Date,
        public school: string,
        public town: string,
        public coach: string,
        public coach_email: string,
        public asst_coach: string,
        public asst_coach_email: string,
        public state: string,
        public competition_id: string,
        public qualifications: {
           id: number,
           match_number: number,
           scor: number,
            results:{
                tank_and_shark_in_target: string
                "shark_touching_tank_only": boolean,
                "nothing_touched_shark": boolean,
                "warning_fence_down": boolean,
                "robot_crossed_fence": boolean,
                "pairs_of_identical_animals": number,
                "pieces_of_food": boolean,
                "wall_supports_gecko": boolean,
                "wall_supports_robot": boolean,
                "milk_and_manure": boolean,
                "milk_only": number,
                "slider_opened": boolean,
                "camera_in_base": boolean,
                "dog_trainer_in_research": boolean,
                "zoologist_in_research": boolean,
                "manure_in_research": boolean,
                "bee_no_honey": boolean,
                "bee_honey_in_base": boolean,
                "prosthesis_not_held_by_ref": "1",
                "prostheses_in_farm": boolean,
                "seal_in_base": boolean,
                "three_milk_in_base": boolean,
                "milk_on_ramp_option": string,
                "all_manure_in_research": boolean,
                "penalties": boolean
            }
        }
    ) { }   
}

//Json Sample
/*
        "team": {
            "id": 1473,
            "fll_number": 156,
            "team_name": "Orange GearTicks",
            "created_at": "2016-11-28T12:10:03.924Z",
            "updated_at": "2016-11-28T12:10:03.924Z",
            "school": null,
            "town": "Lincoln",
            "coach": "Tim Hawkey",
            "coach_email": "tjhawkey@gmail.com",
            "asst_coach": null,
            "asst_coach_email": null,
            "state": "MA",
            "competition_id": 1,
            "qualifications": [
                {
                    "id": 4894,
                    "match_number": 16,
                    "score": 154,
                    "results": {
                        "tank_and_shark_in_target": "T2",
                        "shark_touching_tank_only": "1",
                        "nothing_touched_shark": "1",
                        "warning_fence_down": "1",
                        "robot_crossed_fence": "1",
                        "pairs_of_identical_animals": "3",
                        "pieces_of_food": "2",
                        "wall_supports_gecko": "0",
                        "wall_supports_robot": "0",
                        "milk_and_manure": "0",
                        "milk_only": "1",
                        "slider_opened": "0",
                        "camera_in_base": "0",
                        "dog_trainer_in_research": "0",
                        "zoologist_in_research": "0",
                        "manure_in_research": "0",
                        "bee_no_honey": "0",
                        "bee_honey_in_base": "0",
                        "prosthesis_not_held_by_ref": "1",
                        "prostheses_in_farm": "0",
                        "seal_in_base": "0",
                        "three_milk_in_base": "0",
                        "milk_on_ramp_option": "None",
                        "all_manure_in_research": "0",
                        "penalties": "0"
                    },
                    "team_id": 1473,
                    "created_at": "2016-12-03T15:15:03.696Z",
                    "updated_at": "2016-12-03T15:15:03.696Z",
                    "table_number": 3,
                    "challenge_year": 2016
                },              
            {  
        "id": 4931,
        "match_number": 22,
        "score": 153,
        "results": {
            "tank_and_shark_in_target": "T2",
            "shark_touching_tank_only": "1",
            "nothing_touched_shark": "0",
            "warning_fence_down": "1",
            "robot_crossed_fence": "1",
            "pairs_of_identical_animals": "2",
            "pieces_of_food": "1",
            "wall_supports_gecko": "1",
            "wall_supports_robot": "0",
            "milk_and_manure": "0",
            "milk_only": "1",
            "slider_opened": "0",
            "camera_in_base": "0",
            "dog_trainer_in_research": "1",
            "zoologist_in_research": "1",
            "manure_in_research": "1",
            "bee_no_honey": "1",
            "bee_honey_in_base": "0",
            "prosthesis_not_held_by_ref": "1",
            "prostheses_in_farm": "0",
            "seal_in_base": "0",
            "three_milk_in_base": "0",
            "milk_on_ramp_option": "None",
            "all_manure_in_research": "0",
            "penalties": "0"
        },  */